apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-core
  namespace: monitoring
  labels:
    app: prometheus
    component: core
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus-main
      labels:
        app: prometheus
        component: core
    spec:
      serviceAccountName: prometheus-k8s
      containers:
      - name: prometheus
        image: prom/prometheus:v2.4.3
        args:
          - '--storage.tsdb.retention=72h'
          - '--storage.tsdb.path=/prometheus/data'
          - '--config.file=/prometheus/config/prometheus.yaml'
          - '--web.enable-lifecycle'
          - '--web.enable-admin-api'
          - '--web.console.templates="consoles"'
          - '--web.console.libraries="console_libraries"'
        env:
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: "124"
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 10m
            memory: 150Mi
          # limits:
          #   cpu: 1000m
          #   memory: 1000Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
      # nodeSelector:
      #   prom: "true"
