{
 "title": "Kafka monitor",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Records Rate - Produced/Consumed - 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(km_produce_service_multi_cluster_monitor_records_produced_total{job=\"graphite\"}[1m])",
     "legendFormat": "Produced"
    },
    {
     "expr": "rate(km_consume_service_multi_cluster_monitor_records_consumed_total{job=\"graphite\"}[1m])",
     "legendFormat": "Consumed"
    }
   ]
  },
  {
   "title": "Delay Average Reported",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "km_consume_service_multi_cluster_monitor_records_delay_ms_avg{job=\"graphite\"}",
     "legendFormat": "delay"
    }
   ]
  },
  {
   "title": "duplicated total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "km_consume_service_multi_cluster_monitor_records_duplicated_total{job=\"graphite\"}"
    }
   ]
  },
  {
   "title": "Records Produced Rate 1m - Calculated vs Reported",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(km_produce_service_multi_cluster_monitor_records_produced_total{job=\"graphite\"}[1m])",
     "legendFormat": "calculated"
    },
    {
     "expr": "km_produce_service_multi_cluster_monitor_records_produced_rate{job=\"graphite\"}",
     "legendFormat": "reported"
    }
   ]
  }
 ]
}