apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      name: http
      protocol: TCP
  selector:
    app: grafana
